In [1]:
3*[0]

[0, 0, 0]

In [2]:
range(3)

range(0, 3)

In [4]:
dict(zip(range(3),3*[0]))

{0: 0, 1: 0, 2: 0}

In [8]:
import numpy as np

In [42]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:

prices = {                                                          
   'ACME': 45.23,                                                   
   'AAPL': 612.78,                                                  
   'IBM': 205.55,                                                   
   'HPQ': 37.20,                                                    
   'FB': 10.75                                                      
}                                                                   
# Find min and max price                                            
min_price_key = min(prices, key=lambda k: prices[k])   #股价最低的股票名    
max_price_key = max(prices, key=lambda k: prices[k])

In [116]:
min_price_key

'FB'

In [70]:
np.random.randint(3,4)

3

In [52]:
action_count=dict(zip(range(1,4),3*[0]))

In [53]:
action_count

{1: 0, 2: 0, 3: 0}

In [3]:
a=[1,2,3,2,1,4,2,1,1,4]

In [4]:
def p_choose(p,random):
    sum=0
    for i in p.keys():
        sum=sum+p[i]
        if sum>=random :
            return i

In [6]:
print(p_choose({1:0.3,2:0.4,'44':0.3},0.4))

2


In [92]:
x=np.random.random((4,3,2))
a=np.array([np.identity(2) for x in range(2)])
a_inv=np.linalg.inv(a[1])
b=np.zeros((2,1))
theta=np.dot(a_inv,b)
np.dot(x[1][1],theta)


array([0.])

In [107]:
x[1][1].reshape(-1,1)

array([[0.81945232],
       [0.06262236]])

In [113]:
np.dot(np.dot(x[1][1],a_inv),x[1][1].reshape(-1,1))[0]

0.6754236678708953

In [53]:
a=np.array([np.zeros((2,1)) for x in range(2)])


array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [ ]:

max(self.p,key=lambda k:self.p[k])